import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { Inter } from "@next/font/google";
import Content from "../components/Content";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className="bg-darkblue flex flex-col h-screen min-h-screen">
      <Head>
        <title>Özgenur Özkara</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      {/* Content */}

      <Content />

      {/* Footer */}

      <Footer />
    </div>
  );
}
